name: advance_image_picker
description: Flutter plugin in pure Dart code for selecting/editing multiple images from the Android/iOS image library and taking new pictures with the camera in the same view.
version: 0.1.7+1
homepage: https://freemar.vn
repository: https://github.com/weta-vn/advance_image_picker

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  image: ^3.1.3
  image_cropper: ^2.0.0
  image_editor: ^1.0.2
  path_provider: ^2.0.10
  photo_manager: ^2.5.1+1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icon/
    - assets/images/
